# Generated by Django 3.1.6 on 2021-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ibge', models.CharField(blank=True, max_length=7, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'emp_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=12, null=True)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'emp_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpFilial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=12, null=True)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(blank=True, max_length=80, null=True)),
                ('complemento', models.CharField(blank=True, max_length=40, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'emp_filial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_patrimonio', models.CharField(blank=True, max_length=20, null=True)),
                ('data_aquisicao', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('prazo_garantia_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('prazo_garantia_loja', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoMarca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'equipamento_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'equipamento_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ibge', models.IntegerField(max_length=7)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('renavam', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=12, null=True)),
                ('km_atual', models.IntegerField(blank=True, null=True)),
                ('km_anterior', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoCor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'veiculo_cor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoMarca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'veiculo_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'veiculo_modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoTipoCombustivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'veiculo_tipo_combustivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeiculoTipoVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'veiculo_tipo_veiculo',
                'managed': False,
            },
        ),
    ]
