# Generated by Django 3.1.6 on 2021-02-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDeFpartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'emp_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('id_horario', models.IntegerField()),
                ('id_equipamento', models.IntegerField(blank=True, null=True)),
                ('id_sala', models.IntegerField(blank=True, null=True)),
                ('id_veiculo', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmpDepartamento',
        ),
    ]
