# Generated by Django 3.1.6 on 2021-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210222_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'emp_departamento',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmpDeFpartamento',
        ),
    ]
